dashboard/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.dashboard_view, name='d/dashboard'),
    path('accounts/', views.account_list_view, name='d/account_list'),
    path('accounts/<int:id>/posts/', views.account_posts_view, name='d/account_posts'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list_view, name='post_list'),
    path('post/<int:id>/', views.post_detail_view, name='post_detail'),
    path('post/create/', views.post_create_view, name='post_create'),
    path('post/<int:id>/update/', views.post_update_view, name='post_update'),
    path('post/<int:id>/delete/', views.post_delete_view, name='post_delete'),

    path('comment/<int:id>/update/', views.comment_update_view, name='comment_update'),
    path('comment/<int:id>/delete/', views.comment_delete_view, name='comment_delete'),

    path('post/<int:id>/like/', views.like_add_view, name='like_add'),

    path('post/<int:id>/report/', views.report_create_view, name='report_create'),
    path('post/<int:id>/status/', views.post_status_view, name='post_status')
]

photogram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from register import views as view_reg


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', view_reg.register),
    path('', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.utils import timezone
from user.models import User


class Post(models.Model):
    image = models.ImageField(('image'), upload_to='posts/')
    title = models.CharField(('title'), max_length=50)
    description = models.TextField(('description'), max_length=300, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, blank=True, related_name='likes')
    date_published = models.DateField(('published date'), default=timezone.now)
    is_active = models.BooleanField(('active'), default=True)

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(('comment'), max_length=300)
    date_published = models.DateTimeField(('published date'), default=timezone.now)
    date_updated = models.DateTimeField(('updated date'), blank=True, null=True)

    def __str__(self) -> str:
        return f'Comment {self.pk}'


class Report(models.Model):
    reason = models.CharField(('reason'), max_length=30)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    post_author = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name='post_author')
    report_author = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name='report_author')
    is_agreed = models.BooleanField(('agree'), default=False)
    date_reported = models.DateTimeField(('reported date'), default=timezone.now)

    def __str__(self) -> str:
        return f'Report {self.pk}'

dashboard/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
from user.services import UserService
from main.services import PostService
from user.models import User
from main.models import Post


@login_required
def dashboard_view(request: HttpResponse) -> HttpResponse:
    return render(request, 'dashboard/dashboard_base.html')

@login_required
def account_list_view(request: HttpResponse) -> HttpResponse:
    user_service = UserService()
    accounts: User = user_service.get_objects()

    context = {
        'accounts': accounts,
    }

    return render(request, 'dashboard/accounts.html', context)

@login_required
def account_posts_view(request: HttpResponse, id: int) -> HttpResponse:
    user_service = UserService()
    account: User = user_service.get_object_by_id(id)

    post_service = PostService()
    posts: Post = post_service.filter_objects(id)

    context = {
        'account': account,
        'posts': posts,
    }

    return render(request, 'dashboard/account.html', context)

dashboard/templates/dashboard/account.html
{% extends 'dashboard/dashboard_base.html' %}

{% block content %}
    <div class="d-flex gap-3">
        <div class="bg-dark rounded w-50">
            <div class="d-flex flex-column justify-content-center align-items-center mt-5">
                <img src="{{ account.image.url }}" alt="Avatar" class="rounded mb-3" style="width: 110px; height: 110px;">
                <h5>{{ account.get_full_name }}</h5>
                
                {% if account.role.level == 1 %}
                    <small class="badge text-bg-warning text-white">{{ account.role }}</small>
                {% elif account.role.level >= 3 %}
                    <small class="badge text-bg-danger">{{ account.role }}</small>
                {% else %}
                    <small class="badge text-bg-light">{{ account.role }}</small>
                {% endif %}
            </div>

            <div class="d-flex align-items-center justify-content-center gap-2 mt-3 mb-3">
                <div class="bg-primary rounded" style="padding: 10px 15px;">
                    <i class="bi bi-briefcase"></i>
                </div>
                <div class="d-flex flex-column">
                    <span class="fw-bold">{{ posts.count }}</span>
                    <small class="text-muted">Posts</small>
                </div>
            </div>

            <hr class="m-3">

            <div class="m-3">
                <small class="text-uppercase text-muted fw-light">Details</small>

                <div class="d-flex flex-column gap-1 mt-2">
                    <div>
                        <small class="text-muted">Full name: <span class="text-white">{{ account.get_full_name }}</span></small>
                    </div>
    
                    <div>
                        <small class="text-muted">Email: <span class="text-white">{{ account.email }}</span></small>
                    </div>
                    
                    <div>
                        <small class="text-muted">Status:</small>
                        {% if account.is_active %}
                            <small class="badge text-bg-primary">Active</small>
                        {% else %}
                            <small class="badge text-bg-danger">Inactive</small>
                        {% endif %}
                    </div>
                    
                    <div>
                        <small class="text-muted">Premium:</small>
                        {% if account.is_verified %}
                            <small class="badge text-bg-primary">Verified</small>
                        {% else %}
                            <small class="badge text-bg-danger">Unverified</small>
                        {% endif %}
                    </div>
    
                    <div>
                        <small class="text-muted">Date joined: <span class="text-white">{{ account.date_joined|date:"M j, Y" }}</span></small>
                    </div>
                </div>

                <a class="btn btn-sm btn-outline-danger w-100 mt-3" href="">Suspend</a>
            </div>
        </div>

        <div class="w-100 h-100">
            <div class="mb-2">
                <a class="btn btn-sm btn-outline-primary
                    {% if request.resolver_match.url_name == 'd/account_posts' %}active{% endif %}
                " style="width: 80px;" aria-current="page" href="{% url 'd/account_posts' account.id %}">Posts</a>
                <a class="btn btn-sm btn-outline-primary" style="width: 80px;" href="#">Reports</a>
                <a class="btn btn-sm btn-outline-primary disabled" style="width: 80px;" href="#">Security</a>
            </div>

            <div class="bg-dark rounded">
                <table class="table text-white">
                    <div class="p-2 ms-2">
                        <small class="fs-6">POST LIST</small>
                    </div>
    
                    <caption class="ms-3">
                        <small>TOTAL POSTS:</small>
                        <span class="text-white">{{ posts.count }}</span>
                    </caption>
    
                    <thead class="table-secondary">
                        <tr>
                            <td scope="col"><small>ID</small></td>
                            <td scope="col"><small>TITLE</small></td>
                            <td scope="col"><small>LIKES</small></td>
                            <td scope="col"><small>COMMENTS</small></td>
                            <td scope="col"><small>DATE PUBLISHED</small></td>
                            <td scope="col"></td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in posts %}
                            <tr>
                                <td scope="row"><small>{{ post.id }}</small></td>
                                <td><small>{{ post.title }}</small></td>
                                <td><small>{{ post.likes.count }}</small></td>
                                <td><small>{{ post.comment_set.count }}</small></td>
                                <td><small>{{ post.date_published }}</small></td>
                                <td class="d-flex gap-2">
                                    <a href=""><i class="text-primary bi bi-eye"></i></a>
                                    <a href=""><i class="text-danger bi bi-x-octagon"></i></a>
                                    <a href=""><i class="text-danger bi bi-trash"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/accounts.html
{% extends 'dashboard/dashboard_base.html' %}

{% block content %}
    <div class="bg-dark rounded">
        <table class="table text-white">
            <div class="p-2 ms-2">
                <small class="fs-6">ACCOUNTS LIST</small>
            </div>

            <caption class="ms-3">
                <small>TOTAL ACCOUNTS:</small>
                <span class="text-white">{{ accounts.count }}</span>
            </caption>

            <thead class="table-secondary">
                <tr>
                    <td scope="col"><small>ID</small></td>
                    <td scope="col"><small>USER</small></td>
                    <td scope="col"><small>REPORTS</small></td>
                    <td scope="col"><small>DATE JOINED</small></td>
                    <td scope="col"></td>
                </tr>
            </thead>
            <tbody>
                {% for account in accounts %}
                    <tr>
                        <td scope="row"><small>{{ account.id }}</small></td>
                        <td><small>{{ account.get_full_name }}</small></td>
                        <td><small>12</small></td>
                        <td><small>{{ account.date_joined|date:"M j, Y" }}</small></td>
                        <td class="d-flex gap-2">
                            <a href="{% url 'd/account_posts' account.id %}"><i class="text-primary bi bi-eye"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- <div class="">
        <table class="bg-dark rounded border border-secondary table text-white">
            <tbody class="table-group">            
                {% for account in accounts %}
                    <tr>
                        <td class="d-flex justify-content-between">
                            <div>
                                <h5 class="lead">
                                    {{ account }}
                                    {% if account.is_verified %}
                                        <small><i class="bi bi-patch-check-fill text-primary"></i></small>
                                    {% endif %}
                                </h5>
                                
                                <small class="d-flex align-items-center gap-3">
                                    <span>
                                        <i class="bi bi-collection"></i> {{ account.post_set.count }}
                                    </span>

                                    <span>
                                        <i class="bi bi-exclamation-triangle"></i> 13
                                    </span>
                                </small>
                            </div>

                            <div class="d-flex align-items-center gap-3 me-2">
                                <a href="">
                                    <h3><i class="bi bi-pen"></i></h3>
                                </a>
                                <a href="">
                                    <h3><i class="bi bi-person-dash text-danger"></i></h3>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div> -->
{% endblock %}

dashboard/templates/dashboard/dashboard_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <title>PG - Dashboard</title>
</head>
<body style="background-color: #2f3349;">
    <div>
        <div class="bg-dark fixed-top" style="width: 250px; height: 100vh;">
            <div class="d-flex flex-column justify-content-center align-items-center mt-3 mb-4">
                <img class="rounded" style="width: 150px; height: 150px;" src="{{ user.image.url }}" alt="">
                
                <div class="d-flex flex-column align-items-center text-white mt-2">
                    <h6 class="lead">{{ user }}</h6>
                    
                    {% if user.role.level == 1 %}
                        <small class="badge text-bg-warning">{{ user.role }}</small>
                    {% elif user.role.level >= 3 %}
                        <small class="badge text-bg-danger">{{ user.role }}</small>
                    {% endif %}
                </div>
            </div>
            
            <div class="nav flex-column nav-pills m-3">
                <div class="nav-item">
                    <a class="nav-link
                        {% if request.resolver_match.url_name == 'd/dashboard' %}active{% endif %}
                    " aria-current="page" href="{% url 'd/dashboard' %}">Dashboard</a>
                </div>
                <div class="nav-item">
                    <a class="nav-link" href="#">Analisys</a>
                </div>
                <div class="nav-item">
                    <a class="nav-link
                        {% if request.resolver_match.url_name == 'd/account_list' or request.resolver_match.url_name == 'd/account_posts' %}active{% endif %}
                    " href="{% url 'd/account_list' %}">Accounts</a>
                </div>
                <div class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </div>
            </div>
        </div>

        <div style="margin-left: 250px;">
            <div class="text-white m-3">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>